/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth.signup': RouteRecordInfo<'/auth.signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/errors/access_denied': RouteRecordInfo<'/errors/access_denied', '/errors/access_denied', Record<never, never>, Record<never, never>>,
    '/errors/not_found': RouteRecordInfo<'/errors/not_found', '/errors/not_found', Record<never, never>, Record<never, never>>,
    '/infra_types/': RouteRecordInfo<'/infra_types/', '/infra_types', Record<never, never>, Record<never, never>>,
    '/infra_types/create': RouteRecordInfo<'/infra_types/create', '/infra_types/create', Record<never, never>, Record<never, never>>,
    '/infra_types/edit': RouteRecordInfo<'/infra_types/edit', '/infra_types/edit', Record<never, never>, Record<never, never>>,
    '/infras/': RouteRecordInfo<'/infras/', '/infras', Record<never, never>, Record<never, never>>,
    '/infras/create': RouteRecordInfo<'/infras/create', '/infras/create', Record<never, never>, Record<never, never>>,
    '/infras/detail': RouteRecordInfo<'/infras/detail', '/infras/detail', Record<never, never>, Record<never, never>>,
    '/infras/diagram': RouteRecordInfo<'/infras/diagram', '/infras/diagram', Record<never, never>, Record<never, never>>,
    '/infras/edit': RouteRecordInfo<'/infras/edit', '/infras/edit', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/user/AddUserForm': RouteRecordInfo<'/user/AddUserForm', '/user/AddUserForm', Record<never, never>, Record<never, never>>,
    '/user/UserList': RouteRecordInfo<'/user/UserList', '/user/UserList', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
